name: Close Issue on Commit

on:
  push:
    branches:
      - develop

jobs:
  close-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Close issue
        if: contains(github.event.head_commit.message, '#')
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.head_commit.message }}" | grep -o '#[0-9]\+' | tr -d '#')
          if [ -n "$ISSUE_NUMBER" ]; then
            curl -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER \
              -d '{"state":"closed"}'
          fi
